CREATE DATABASE bd;
USE bd;
CREATE TABLE IF NOT EXISTS usuarios(
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(60) UNIQUE NOT NULL,
	ID_Usuario INT UNIQUE NOT NULL AUTO_INCREMENT,
    senha VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Usuario)
);

CREATE TABLE IF NOT EXISTS quadros(
	ID_Quadros INT NOT NULL AUTO_INCREMENT,
    ID_Usuario INT NOT NULL,
    imagem LONGBLOB NOT NULL,
    autor VARCHAR(60) NOT NULL,
    ano_obra INT NOT NULL,
    titulo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    PRIMARY KEY(ID_Quadros),
    CONSTRAINT fk_UserQuadros FOREIGN KEY (ID_Usuario) REFERENCES usuarios (ID_Usuario)
);